spark.sql.extensions                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lab                  org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lab.type             hadoop
spark.sql.catalog.lab.warehouse        file:/home/iceberg/warehouse
spark.sql.defaultCatalog               lab
spark.eventLog.enabled                 true
spark.eventLog.dir                     /home/iceberg/spark-events
spark.history.fs.logDirectory          /home/iceberg/spark-events
spark.sql.catalogImplementation        in-memory